# Generated by Django 3.2.2 on 2021-05-12 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venda_imoveis_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venda_imoveis_app.imovel'),
        ),
    ]
